export const ACTIONS = ({
  START_LOADING: 'START_LOADING',
  GENERATE_RANDOM_PHONE_NUMBERS: 'GENERATE_RANDOM_PHONE_NUMBERS',
  GENERATE_RANDOM_PHONE_NUMBERS_ERROR: 'GENERATE_RANDOM_PHONE_NUMBERS_ERROR'
});
